apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployaks01
  labels:
    app: autodeployaks01
  namespace: namespace-workflow-1708345637146
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployaks01
  template:
    metadata:
      labels:
        app: autodeployaks01
    spec:
      containers:
        - name: autodeployaks01
          image: acrworkflow1708345637146.azurecr.io/image-workflow-1708345637146:latest
          ports:
            - containerPort: 5000