apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployAKS
  labels:
    app: autodeployAKS
  namespace: namespace-workflow-1708344733767
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployAKS
  template:
    metadata:
      labels:
        app: autodeployAKS
    spec:
      containers:
        - name: autodeployAKS
          image: acrworkflow1708344733767.azurecr.io/image-workflow-1708344733767:latest
          ports:
            - containerPort: 5000