apiVersion: v1
kind: Service
metadata:
  name: autodeployAKS
  namespace: namespace-workflow-1708344733767
spec:
  type: LoadBalancer
  selector:
    app: autodeployAKS
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000