apiVersion: v1
kind: Service
metadata:
  name: autodeployaks01
  namespace: namespace-workflow-1708345637146
spec:
  type: LoadBalancer
  selector:
    app: autodeployaks01
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000